server:
  userport: 8080
rpc:
  port: 9090
database:
  dsn: "user:password@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
rabbitmq:
  addr: "127.0.0.1:5672"
  user: "guest"
  password: "guest"
